### ISSUE TITLE
Error in section "Saving Extracted Features (optional)" in Notebook 3 

### ISSUE THREAD

**Issue by thuoctran** [jaron/deep-listening#2]
Hi,
I am trying to the 3-us8k-cnn-extract-train, but at the section "Saving Extracted Features (optional)", I got this results:

Saving fold1
Features of fold1  =  (0, 60, 41, 2)
Labels of fold1  =  (0, 0)
Saved data/us8k-np-cnn/fold1_x.npy
Saved data/us8k-np-cnn/fold1_y.npy

Saving fold2
Features of fold2  =  (0, 60, 41, 2)
Labels of fold2  =  (0, 0)
Saved data/us8k-np-cnn/fold2_x.npy
Saved data/us8k-np-cnn/fold2_y.npy

Saving fold3
Features of fold3  =  (0, 60, 41, 2)
Labels of fold3  =  (0, 0)
Saved data/us8k-np-cnn/fold3_x.npy
Saved data/us8k-np-cnn/fold3_y.npy

Saving fold4
Features of fold4  =  (0, 60, 41, 2)
Labels of fold4  =  (0, 0)
Saved data/us8k-np-cnn/fold4_x.npy
Saved data/us8k-np-cnn/fold4_y.npy

Saving fold5
Features of fold5  =  (0, 60, 41, 2)
Labels of fold5  =  (0, 0)
Saved data/us8k-np-cnn/fold5_x.npy
Saved data/us8k-np-cnn/fold5_y.npy

Saving fold6
Features of fold6  =  (0, 60, 41, 2)
Labels of fold6  =  (0, 0)
Saved data/us8k-np-cnn/fold6_x.npy
Saved data/us8k-np-cnn/fold6_y.npy

Saving fold7
Features of fold7  =  (0, 60, 41, 2)
Labels of fold7  =  (0, 0)
Saved data/us8k-np-cnn/fold7_x.npy
Saved data/us8k-np-cnn/fold7_y.npy

Saving fold8
Features of fold8  =  (0, 60, 41, 2)
Labels of fold8  =  (0, 0)
Saved data/us8k-np-cnn/fold8_x.npy
Saved data/us8k-np-cnn/fold8_y.npy

Saving fold9
Features of fold9  =  (0, 60, 41, 2)
Labels of fold9  =  (0, 0)
Saved data/us8k-np-cnn/fold9_x.npy
Saved data/us8k-np-cnn/fold9_y.npy

Saving fold10
Features of fold10  =  (0, 60, 41, 2)
Labels of fold10  =  (0, 0)
Saved data/us8k-np-cnn/fold10_x.npy
Saved data/us8k-np-cnn/fold10_y.npy

I think it's a problem causing a later error on "Training on a minimised data set" section.

---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-9-d3b32dc150e3> in <module>()
      2 
      3 # load fold1 for testing
----> 4 train_x, train_y = load_folds([1])
      5 
      6 # load fold2 for validation

<ipython-input-5-77edf08909b1> in load_folds(folds)
     42         feature_file = os.path.join(data_dir, fold_name + '_x.npy')
     43         labels_file = os.path.join(data_dir, fold_name + '_y.npy')
---> 44         loaded_features = np.load(feature_file)
     45         loaded_labels = np.load(labels_file)
     46         print fold_name, "features: ", loaded_features.shape

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/npyio.pyc in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    427             except:
    428                 raise IOError(
--> 429                     "Failed to interpret file %s as a pickle" % repr(file))
    430     finally:
    431         if own_fid:

IOError: Failed to interpret file 'data/us8k-np-cnn-mini/fold1_x.npy' as a pickle

Many thanks for the helps!

**Comment by jaron** [comment]
It looks like the extraction process is failing somehow. 

If you look at the sizes of each fold, you'll see you're getting (0, 60, 41, 2), but that first number shouldn't be a zero, you should have hundreds of those features, depending on the number of folds you create.  For instance, when I create 3 folds, I see the following:

```
Saving fold1
Features of fold1  =  (2400, 60, 41, 2)
Labels of fold1  =  (2400, 10)
Saved data/us8k-np-cnn-mini/fold1_x.npy
Saved data/us8k-np-cnn-mini/fold1_y.npy

Saving fold2
Features of fold2  =  (2076, 60, 41, 2)
Labels of fold2  =  (2076, 10)
Saved data/us8k-np-cnn-mini/fold2_x.npy
Saved data/us8k-np-cnn-mini/fold2_y.npy

Saving fold3
Features of fold3  =  (2371, 60, 41, 2)
Labels of fold3  =  (2371, 10)
Saved data/us8k-np-cnn-mini/fold3_x.npy
Saved data/us8k-np-cnn-mini/fold3_y.npy
```

I strongly suspect you haven't downloaded the UrbanSound8K audio files. You can only run the code in the "Saving Extracted Features (optional)" cell if you've got those files. You don't actually need them, that's why I included a smaller set of pre-processing features in pickle format in the  data/us8k-np-cnn-mini directory.

If you don't have the full UrbanSound8k data set, don't run the "Saving Extracted Features (optional)" cell. And just ensure the first line in the "Training on a minimised data set" cell is 

data_dir = "data/us8k-np-cnn-mini"

And it should work for you.

**Comment by thuoctran** [comment]
Thank you for your help. The problem is solved. But I meet another problem.
 In a determin the ROC AUC score part,

def evaluate(model):
    y_prob = model.predict_proba(test_x, verbose=0)
    y_pred = np_utils.probas_to_classes(y_prob)
    y_true = np.argmax(test_y, 1)

the problem is a function np_utils.probas_to_classes(y_prob).

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-a1db5e44a1e9> in <module>()
     46         # now evaluate the trained model against the unseen test data
     47         print("Evaluating model...")
---> 48         roc, acc = evaluate(model)
     49         av_roc += roc
     50         av_acc += acc

<ipython-input-5-52f0bd6a8c6f> in evaluate(model)
      1 def evaluate(model):
      2     y_prob = model.predict_proba(test_x, verbose=0)
----> 3     y_pred = np_utils.probas_to_classes(y_prob)
      4     y_true = np.argmax(test_y, 1)
      5 

AttributeError: 'module' object has no attribute 'probas_to_classes'

**Comment by jaron** [comment]
That sounds like a Keras versioning issue, I assume you're using a more recent version, I think the code in the repo was based on Keras 1.0. 

You could try adding this line:
`from keras.utils.np_utils import probas_to_classes`

That apparently works for Keras 1.2.0. 
I think it's different in Keras 2.0, so if that doesn't work let me know your Keras version.

**Comment by thuoctran** [comment]
I've tried to add from keras.utils.np_utils import probas_to_classes but it showed ImportError: cannot import name probas_to_classes.

I'm using the latest Keras version 2.0.6.

**Comment by jaron** [comment]
Yes, there's been a few package changes in Keras 2. I've updated notebook 3 to use the latest Keras and Tensorflow, and made it Python3 compatible as well. Hopefully you should be able to run it now. I'll update the other notebooks over the next few days.

**Comment by jaron** [comment]
Updated to use Keras 2, closing issue

**Comment by hibakhanam** [comment]
hi thuoctran , how you solved your first issue (features not extracted properly) i am also facing the same problem and i downloaded the complete dataset 
![code](https://user-images.githubusercontent.com/39904968/41093186-13dc64c0-6a64-11e8-921a-c57f05c9fd40.PNG)
![output](https://user-images.githubusercontent.com/39904968/41093224-3385eb16-6a64-11e8-9a2b-3cace3673e7b.png)
