### ISSUE TITLE
How is number of frames in a window set during feature extraction(melspectogram)

### ISSUE THREAD

**Issue by SivaKanishka** [jaron/deep-listening#3]
@jaron Can you please explain how number of frames in each window is set in 3-us8k-cnn-extract-train.ipynb script. To be exact, I am referring to **extract_features** method. I understand that the script is creating overlapping windows from **windows** method, but I don't understand how librosa library is able to adjust frames with **librosa.feature.melspectrogram** function (script doesn't explicitly set number of frames in a window). I tried looking at librosa documentation, but no luck in getting the answer.

Thanks

**Comment by jaron** [comment]
The number of frames is a consequence of the fixed size input, rather than any parameter supplied to librosa. You'll notice in the extract_features function, the bands and frames parameters have defaults, to split each sound clip into 41 overlapping frames, one for each of the 60 mel-bands, giving an array of 60 rows and 41 columns. Does that make sense?

**Comment by SivaKanishka** [comment]
@jaron Thank you for the reply. I will explain my thought process in understanding the feature extraction process, please correct me if I am wrong.

**Requirement**
The feature extraction implementation should give a melspectrogram (in each window) of 41 frames. Each frame corresponds to 25 milli second time interval with 60 frequency bands.

**Code implementation**
- Each audio file is loaded using librosa with a sampling rate of 22050 (default)
- ```512 * (frames -1)``` gets 20,480 data points in the audio file. This is essentially a window.

**My question** 
- When this window (data points) is passed to ```librosa.feature.melspectrogram``` function, We have passed only number of bands as an argument to this function. How did it figure out number frames to fix in this window?

Thanks

**Comment by jaron** [comment]
You can see the calculation in the melspectrogram implementation itself at:
https://github.com/librosa/librosa/blob/master/librosa/feature/spectral.py
which uses the _spectrogram function from:
https://github.com/librosa/librosa/blob/master/librosa/core/spectrum.py

Looks like n_fft (length of the FFT window) = 2 * (S.shape[0] - 1)
where S is the spectrogram

**Comment by SivaKanishka** [comment]
@jaron Thank you for pointing to the source code. It helped a lot in understanding the implementation
